listener:
  interface: tun0
  lport: 443
  webroot: /var/www/html

ps_tools:
  adpeas:
    location: adPEAS.ps1
    cmd: Invoke-adPEAS
  getuserspns:
    location: tools/GetUserSPNs.ps1
  hostrecon:
    location: tools/HostRecon.ps1
    cmd: Invoke-HostRecon
  lapstoolkit:
    location: tools/LAPSToolkit.ps1
    cmd: Get-LAPSComputers
  powermad:
    location: tools/powermad.ps1
  powersharppack:
    location: tools/PowerSharpPack/PowerSharpPack.ps1
    cmd: PowerSharpPack -seatbelt
  powerupsql:
    location: tools/PowerUpSQL.ps1
    cmd: Invoke-SQLAudit
  powerview:
    location: tools/powerview.ps1
  runtxt:
    location: run.txt
  sharpsploit-ps:
    location: tools/PowerSharpPack/PowerSharpBinaries/Invoke-SharpSploit.ps1
    alt: powersharppack
  winpwn:
    location: tools/Offline_WinPwn.ps1
    cmd: WinPwn

zip_tools:
  sysinternals:
    location: tools/sysinternals.zip
  mimikatz:
    location: tools/mimikatz.zip

cs_tools:
  winpeas:
    location: tools/winPEASx64.exe
    class: winPEAS.Program
    alt: powersharppack
  efspotato:
    location: EfsPotato.exe
    class: EfsPotato.Program
    cmd: STAGER_URL
  metdll:
    location: met.dll
    class: LeMans.Class1
    entrypoint: Ferarri
  metexe:
    location: met.exe
    class: LeMans.Class1
  pslessexec:
    location: tools/PSLessExec.exe
    class: PSLessExec.Program
  rubeus:
    location: tools/Rubeus.exe
    class: Rubeus.Program
    cmd: triage
    alt: powersharppack
  seatbelt:
    location: tools/Seatbelt.exe
    class: Seatbelt.Program
    cmd: -group=system
    alt: powersharppack
  sharpsploit:
    location: tools/SharpSploit.exe
    class: SharpSploit.Program
    alt: powersharppack
  spoolsample:
    location: tools/SpoolSample.exe
    class: SpoolSample.Program
    alt: powersharppack
  sharppersist:
    location: tools/SharpPersist.exe
    class: SharPersist.Program
    alt: powersharppack
  sqlclient:
    location: tools/SQLClient.exe
    class: SQLClient.Program
  sharpup:
    location: tools/SharpUp.exe
    class: SharpUp.Program
    cmd: audit
    alt: powersharppack
  sharphound:
    location: tools/SharpHound.exe
    class: SharpHound.Program
    alt: powersharppack
